FROM envoyproxy/envoy-dev:latest

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*
COPY ./front-envoy.yml /etc/front-envoy.yml
RUN chmod go+r /etc/front-envoy.yml
CMD ["/usr/local/bin/envoy", "-c", "/etc/front-envoy.yml", "--service-cluster", "front-proxy"]