version: '3'

services:
  service1:
    build: 
      context: service1
      dockerfile: ../Dockerfile
    environment:
      - PORT=3000
    networks:
      - mstest
    deploy:
      replicas: 50
  service2:
    build: 
      context: service2
      dockerfile: ../Dockerfile
    environment:
      - PORT=3001
    networks:
      - mstest
    deploy:
      replicas: 50

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    networks:
    - mstest
    ports:
    - "8000:8000"
    - "8001:8001"

  service1_elb:
    image: nginx:latest
    volumes:
      - ./service1/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
    networks:
      - mstest

  service2_elb:
    image: nginx:latest
    volumes:
      - ./service2/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service2
    networks:
      - mstest

networks:
  mstest:
    driver: bridge